// `:::note ... :::` directive from the AI-markdown contract, as an
// editable container node. Its `color` attribute is filled in by
// NovaHeadingExtension's rescan plugin (same mechanism as headings),
// so it always matches its enclosing section without its own logic.
//
// Markdown parsing/serialization is generated by createBlockMarkdownSpec
// — this was MISSING before, which is why ":::note" was showing up as
// literal plain text instead of becoming a real node.

import {
  Node,
  mergeAttributes,
  createBlockMarkdownSpec,
  wrappingInputRule,
} from "@tiptap/core";

export const NovaAdmonition = Node.create({
  name: "novaNote",
  group: "block",
  content: "block+",
  defining: true,

  addInputRules() {
    return [
      wrappingInputRule({
        find: /^:::note\s$/,
        type: this.type,
      }),
    ];
  },

  addAttributes() {
    return {
      color: {
        default: null,
        parseHTML: (element) => element.getAttribute("data-color"),
        renderHTML: (attrs) =>
          attrs.color ? { "data-color": attrs.color } : {},
      },
      type: {
        default: "note",
        parseHTML: (element) => element.getAttribute("data-type") || "note",
        renderHTML: (attrs) => (attrs.type ? { "data-type": attrs.type } : {}),
      },
    };
  },

  parseHTML() {
    return [{ tag: 'div[data-nova-block="note"]' }];
  },

  renderHTML({ HTMLAttributes }) {
    return [
      "div",
      mergeAttributes(HTMLAttributes, {
        "data-nova-block": "note",
        class: "nova-note",
      }),
      0,
    ];
  },

  ...createBlockMarkdownSpec({
    nodeName: "novaNote",
    name: "note",
    content: "block",
    defaultAttributes: { type: "note" },
    allowedAttributes: ["type"], // color excluded — computed, never authored/persisted
  }),
});
